services:
  # mongodb:
  #   image: 'mongo'
  #   container_name: mongodb
  #   ports:
  #     - '27017:27017'

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=vmc_student_portal
    volumes:
      # Keep this: It mounts your scripts to be run ONCE at startup
      - ./db-setup:/docker-entrypoint-initdb.d:ro
    # No "volumes" mapping to /var/lib/mysql here = ephemeral data