services:
  # mongodb:
  #   image: 'mongo'
  #   container_name: mongodb
  #   ports:
  #     - '27017:27017'

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      # Use this to allow root with NO password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=vmc_student_portal
    volumes:
      - ./db-setup:/docker-entrypoint-initdb.d

volumes:
  mysql_data: